name: Test Project
on:
  push:
    branches:
      - main
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: installing node
        run: echo "installing node..."
      - name: testing
        run: echo "testing..."
      - name: Deploy to prod
        uses: ./.github/workflows/deploy.yml
  