name: Test Project
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      user_input:
        description: 'User input'
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: GetCode
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install Dependencies
        run: npm ci
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GetCode
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: deploy to prod
        run: echo "deploying"